### ISSUE TITLE
Proofreading checklist

### ISSUE THREAD

**Issue by eah13** [csev/py4e#93]
Things I've encountered as one-offs that I'll Ctrl-f for in all chapters:
- [x] remove all `u'unicode strings'` since Python 3 is unicode by default (esp chapter 14)
- [ ] make sure all markdown links have http:// in the URL
- [ ] explain `u'` vs `b'` in Python 2 & 3 at the appropriate points.  The python docs have a great explanation of urllib [here](https://docs.python.org/3.1/library/urllib.request.html#examples):

> Note that urlopen returns a bytes object. This is because there is no way for urlopen to automatically determine the encoding of the byte stream it receives from the http server. In general, a program will decode the returned bytes object to string once it determines or guesses the appropriate encoding.
- [ ] Bad hyphens and any other character problems.  Just saw this bad hyphen in chapter 12:

![screenshot 2016-02-14 at 9 19 17 pm](https://cloud.githubusercontent.com/assets/1702745/13038438/d8e3ee52-d360-11e5-959d-5b005f2208c9.png)

There may be other problem characters.  Once they're found it's an easy job to go replace them with the right char.

**Comment by eah13** [comment]
(Added bad hyphens to list)
